<?php

return [
    // 'source' => env('ANALYTICS_VIEW_ID', '89090231'),
    'source' => [
        ['category'=>'Paid Marketing', 'medium'=>'Search-Ads', 'source'=>'Google-Text'],
        ['category'=>'Paid Marketing', 'medium'=>'Search-Ads', 'source'=>'Google-Smart'],
        ['category'=>'Paid Marketing', 'medium'=>'Display-Ads', 'source'=>'Google-Dsp'],
        ['category'=>'Paid Marketing', 'medium'=>'Display-Ads', 'source'=>'Google-Disc'],
        ['category'=>'Paid Marketing', 'medium'=>'Video Ads', 'source'=>'Youtube-Ads'],
        ['category'=>'Paid Marketing', 'medium'=>'Social Ads', 'source'=>'Facebook-Ads'],
        ['category'=>'Paid Marketing', 'medium'=>'Social Ads', 'source'=>'Linkedin-Ads'],
        ['category'=>'Paid Marketing', 'medium'=>'Social Ads', 'source'=>'Twitter-Ads'],
        ['category'=>'Paid Marketing', 'medium'=>'Social Ads', 'source'=>'Instagram-Ads'],
        ['category'=>'Paid Marketing', 'medium'=>'ReTargeting Ads', 'source'=>'Criteo'],
        ['category'=>'Paid Marketing', 'medium'=>'Native Ads', 'source'=>'Taboola'],
        ['category'=>'Paid Marketing', 'medium'=>'Native Ads', 'source'=>'Columbia'],
        ['category'=>'Paid Marketing', 'medium'=>'Native Ads', 'source'=>'Adgebra'],
        ['category'=>'Paid Marketing', 'medium'=>'Native Ads', 'source'=>'MountingDigital'],
        ['category'=>'Paid Marketing', 'medium'=>'Native Ads', 'source'=>'Outbrain'],
        ['category'=>'Paid Marketing', 'medium'=>'Native Ads', 'source'=>'DailyHunt'],
        ['category'=>'Paid Marketing', 'medium'=>'Native Ads', 'source'=>'Hypermarketing'],
        
        ['category'=>'Paid Marketing', 'medium'=>'In-app Ads', 'source'=>' Zomato-Ads'],
        
        ['category'=>'Paid Marketing', 'medium'=>'In-app Ads', 'source'=>'Swiggy-Ads'],
        ['category'=>'Paid Marketing', 'medium'=>'In-app Ads', 'source'=>'Snap-Chat'],
        ['category'=>'Paid Marketing', 'medium'=>'In-app Ads', 'source'=>'Dunzo-Ads'],
        
        
        ['category'=>'Paid Marketing', 'medium'=>'Agency Ads', 'source'=>'Webdura'],
        ['category'=>'Paid Marketing', 'medium'=>'Agency Ads', 'source'=>'Media Qart'],
        ['category'=>'Paid Marketing', 'medium'=>'Agency Ads', 'source'=>'Prop Story'],
        ['category'=>'Paid Marketing', 'medium'=>'Agency Ads', 'source'=>'O3M'],
        ['category'=>'Paid Marketing', 'medium'=>'Agency Ads', 'source'=>'3DM'],
        ['category'=>'Paid Marketing', 'medium'=>'Agency Ads', 'source'=>'Realathe'],
        ['category'=>'Paid Marketing', 'medium'=>'Agency Ads', 'source'=>'GenY'],
        ['category'=>'Paid Marketing', 'medium'=>'Agency Ads', 'source'=>'CamDev'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'99acres'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'MagicBricks'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'Housing'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'IndiaProperty'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'ChennaiProperties'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'CommonFloor'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'Roof&floor'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'Zricks'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'Sulekha'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'TimesInternetAggregators'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'Zoom Blind'],
        ['category'=>'Paid Marketing', 'medium'=>'Aggregators', 'source'=>'NoBroker'],
        ['category'=>'Organic Marketing', 'medium'=>'IM Support', 'source'=>'Webchat'],
        ['category'=>'Organic Marketing', 'medium'=>'IM Support', 'source'=>'Whatsapp-Digital'],
        ['category'=>'Organic Marketing', 'medium'=>'IM Support', 'source'=>'SMS-Digital'],
        ['category'=>'Organic Marketing', 'medium'=>'Search Organic', 'source'=>'SEO'],
        ['category'=>'Organic Marketing', 'medium'=>'Search Organic', 'source'=>'GBL'],
        ['category'=>'Organic Marketing', 'medium'=>'Social Organic', 'source'=>'Social-Posts'],
        ['category'=>'Organic Marketing', 'medium'=>'Social Organic', 'source'=>'Social-Profile'],
        ['category'=>'Organic Marketing', 'medium'=>'Social Organic', 'source'=>'FB-Marketplace'],
        ['category'=>'Organic Marketing', 'medium'=>'Social Organic', 'source'=>'FB-Commenting'],
        ['category'=>'Organic Marketing', 'medium'=>'Listing Aggregators', 'source'=>'ClickIndia-Listing'],
        ['category'=>'Organic Marketing', 'medium'=>'Listing Aggregators', 'source'=>'Makaan-Listing'],
        ['category'=>'Organic Marketing', 'medium'=>'Listing Aggregators', 'source'=>'Propertywala-Listing'],
        ['category'=>'Organic Marketing', 'medium'=>'Listing Aggregators', 'source'=>'MyPropertyBoutique-Listing'],
        ['category'=>'Organic Marketing', 'medium'=>'Listing Aggregators', 'source'=>'Quickr-Listing'],
        ['category'=>'Organic Marketing', 'medium'=>'Direct Traffic', 'source'=>'DirectTraffic'],
        ['category'=>'Organic Marketing', 'medium'=>'Referral Sites', 'source'=>'To be created Dynamically'],
        ['category'=>'Organic Marketing', 'medium'=>'Backlinks', 'source'=>'Source has to be defined in UTM_Source'],
        ['category'=>'Organic Marketing', 'medium'=>'Internal Sites', 'source'=>'JS -Website'],
        ['category'=>'Organic Marketing', 'medium'=>'Internal Sites', 'source'=>'JR -Website'],
        ['category'=>'Organic Marketing', 'medium'=>'Internal Sites', 'source'=>'HG -Website'],
        ['category'=>'Organic Marketing', 'medium'=>'Internal Sites', 'source'=>'AGR-Website'],
        ['category'=>'Organic Marketing', 'medium'=>'Internal Sites', 'source'=>'Eternity-Website'],
        ['category'=>'Organic Marketing', 'medium'=>'Internal Sites', 'source'=>'VIB-Website'],
        ['category'=>'Organic Marketing', 'medium'=>'Internal Sites', 'source'=>'CNCB-Website'],
        ['category'=>'Organic Marketing', 'medium'=>'Q&A', 'source'=>'Quora'],
        ['category'=>'Organic Marketing', 'medium'=>'Corporate Website', 'source'=>'LP-Alliance-Website'],
        ['category'=>'Organic Marketing', 'medium'=>'Corporate Website', 'source'=>'LP-Urbanrise-Website'],
        ['category'=>'Paid Marketing', 'medium'=>'Geo Fencing', 'source'=>'GeoFencing'],
        ['category'=>'Paid Marketing', 'medium'=>'Programmatic Ads', 'source'=>'Programmatic-Ads'],
        ['category'=>'Paid Marketing', 'medium'=>'OTT Platform', 'source'=>'Hotstar-Ads'],
        ['category'=>'Paid Marketing', 'medium'=>'OTT Platform', 'source'=>'Zee5-Ads'],
        ['category'=>'Organic Marketing', 'medium'=>'Email Marketing-Int', 'source'=>'Internal-Email-Campaign'],
        ['category'=>'Paid Marketing', 'medium'=>'Email Marketing-Ext', 'source'=>'External-Email-Campaign'],
        ['category'=>'Organic Marketing', 'medium'=>'Video Promotion', 'source'=>'YouTube'],
        ['category'=>'Organic Marketing', 'medium'=>'Video Promotion', 'source'=>'Vimeo'],
        ['category'=>'Organic Marketing', 'medium'=>'Video Promotion', 'source'=>'DailyMotion'],
    ],
    'campaign' => [
        ['name' => 'FB Commenting'],
        ['name' => 'GBL Commenting'],
    ],
    'projects' => [
        'AGR' => 'agr',
        'HG' => 'hg',
        'OS' => 'os',
        'VIB' => 'vib',
        'Eternity' => 'eternity',
        'Padur' => 'padur',
        'JS' => 'js',
        'Siruseri' => 'siruseri',
        'JR' => 'jr',
        'Ameenpur' => 'ameenpur',
        'Bachupally' => 'bachupally',
        'Gandimaisamma' => 'gandimaisamma',
        'TSAI Apartments' => 'tsai',
    ],
];
